#!/bin/bash
# DESC: prepare EL7 Server for oracle 12c installation and guides trough install process
# $Author: chris $
# $Revision: 1.3 $
# $RCSfile: oracle-12c-install.sh,v $
#
#########################################################################################
# Copyright (c) Chris Ruettimann <chris@bitbull.ch>

# This software is licensed to you under the GNU General Public License.
# There is NO WARRANTY for this software, express or
# implied, including the implied warranties of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. You should have received a copy of GPLv2
# along with this software; if not, see
# http://www.gnu.org/licenses/gpl.txt

# installation root
ROOT=/srv
# installation base dir
IBASE=$ROOT/u00/setup/12.1.0SE
# unzip installer cds here before you start:
# mkdir -p $IBASE
# cd $IBASE
# unzip linuxamd64_12102_database_se2_1of2.zip
# unzip linuxamd64_12102_database_se2_2of2.zip

OIP=$(ip a | grep inet\ | grep -v 127 | awk '{print $2}' | cut -d/ -f1)

SID=TST1
ORACLE_SID=$SID
ORA_APP=$ROOT/u00/app
# oracle base dir
OBASE=$ROOT/u00/app/oracle
# oracle home
OHOME=$OBASE/product/12.1.0/db1
# dbfiles, redolog1, controlfile1
DATA1=$ROOT/u01/oradata
# redolog2, controlfile2
DATA2=$ROOT/u02/oradata
# archive logs
ARCH=$ROOT/u03/arch
# controlfile3, redolog3
DATA3=$ROOT/u03/oradata
# backup dest
BKP=$ROOT/u04/flash

#######################################################################
# install software deps
#######################################################################
yum makecache
yum -y upgrade
yum -y install libaio compat-db compat-libcap1 glibc-devel libXtst libXtst.i686 xauth libXp glibc-devel.i686 vnc-server \
compat-libstdc++-33 make mksh gcc openmotif gcc-c++ libaio-devel libstdc++-devel \
compat-libstdc++-33 sysstat unixODBC unixODBC-devel elfutils-libelf-devel \
acpid sysstat dstat tcpdump screen vim-enhanced strace ltrace ethtool curl wget NetworkManager-tui \
system-config-firewall-tui chrony net-tools net-snmp net-snmp-utils net-snmp-sysvinit openssh-server-sysvinit \
postfix-sysvinit.noarch postfix sysvinit-tools rsync unzip bzip2 zip perl lsof rpm-cron mailx xterm

# only one from epel repo
yum -y install http://dl.fedoraproject.org/pub/epel/7/x86_64/r/rlwrap-0.42-1.el7.x86_64.rpm

systemctl disable gdm.service
systemctl disable kdump.service
systemctl enable acpid

#######################################################################
# sshd config
#######################################################################
# grep -q '^PermitRootLogin' /etc/ssh/sshd_config || echo 'PermitRootLogin without-password' >> /etc/ssh/sshd_config
# sed -i 's/^PermitRootLogin.*/PermitRootLogin without-password/g' /etc/ssh/sshd_config
grep -q '^UseDNS' /etc/ssh/sshd_config || echo 'UseDNS no' >> /etc/ssh/sshd_config
sed -i 's/^UseDNS.*/UseDNS no/g' /etc/ssh/sshd_config
grep -q '^GSSAPIAuthentication' /etc/ssh/sshd_config || echo 'GSSAPIAuthentication no' >> /etc/ssh/sshd_config
sed -i 's/^GSSAPIAuthentication.*/GSSAPIAuthentication no/g' /etc/ssh/sshd_config
systemctl enable sshd.service

#######################################################################
# enable serial console for virsh console access
#######################################################################
lsmod | grep -v grep | grep -q virtio_console
if [ $? -eq 0 ] ; then
grep -q '^GRUB_CMDLINE_LINUX.*console=ttyS0' /etc/default/grub || sed -i 's/^GRUB_CMDLINE_LINUX.*/GRUB_CMDLINE_LINUX="vconsole.font=latarcyrheb-sun16 vconsole.keymap=sg crashkernel=auto console=tty0 console=ttyS0,115200"/g' /etc/default/grub
grub2-mkconfig -o /boot/grub2/grub.cfg
fi

#######################################################################
# set hosts file
#######################################################################
echo "# generated by oracle installer
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
$OIP   $(hostname -s)
" > /etc/hosts

#######################################################################
# disable selinux
#######################################################################
sed -i 's/SELINUX=.*/SELINUX=permissive/g' /etc/selinux/config
setenforce 0

#######################################################################
# create user and group
#######################################################################
mkdir -p $ROOT/u00/home
groupadd -g 400 dba
useradd -u 400 -g 400 -d $ROOT/u00/home/oracle -s /bin/bash -c "Oracle Owner" oracle
mkdir -p $ROOT/u00/home/oracle/admin/sqlnet

#######################################################################
# create directory structure based on oracle OFA standard
#######################################################################
#oracle home
mkdir -p $OHOME
mkdir -p $DATA1/$SID $DATA2/$SID $DATA3/$SID $ARCH $BKP

chown -R oracle:dba $ROOT/u*
chown -R oracle:dba $ROOT/u*

#######################################################################
# set and activate kernel configuration
#######################################################################
echo '
# Kernel Parameters for Oracle 12
kernel.shmall = 2097152
# shmmax for 4GB RAM VM
kernel.shmmax = 1987794944
kernel.shmmni = 4096
kernel.sem = 250 32000 100 128
fs.file-max = 6815744
net.ipv4.ip_local_port_range = 9000 65500
net.core.rmem_default = 262144
net.core.rmem_max = 4194304
net.core.wmem_default = 262144
net.core.wmem_max = 1048576
fs.aio-max-nr = 1048576
' >> /etc/sysctl.conf

sysctl -p

#######################################################################
# change system limitation settings for user oracle
#######################################################################
echo '
# To increase the shell limits for Oracle 11g
oracle soft nproc 2047
oracle hard nproc 16384
oracle soft nofile 1024
oracle hard nofile 65536
' >> /etc/security/limits.conf

#######################################################################
# create base env for oracle user
#######################################################################
echo "# .bashrc
# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# Oracle specific aliases and functions
export ORACLE_HOSTNAME=$(hostname -s)
export ORACLE_SID=$SID
export ORACLE_UNQNAME=\$ORACLE_SID
export LISTENER_NAME=\$ORACLE_SID
export ORACLE_BASE=$OBASE
export ORACLE_HOME=$OHOME
export ORACLE_DOC=\$ORACLE_HOME/doc
export ORACLE_ADMIN=\$ORACLE_HOME/network/admin
export TNS_ADMIN=\$ORACLE_HOME/network/admin/sqlnet
export PATH=\$ORACLE_HOME/bin:\$HOME/bin:\$PATH
export CLASSPATH=\$ORACLE_HOME/JRE:\$ORACLE_HOME/jlib:\$ORACLE_HOME/rdbms/jlib
export LD_LIBRARY_PATH=\$ORACLE_HOME/lib:\$LD_LIBRARY_PATH
export LANG=en_US.UTF-8
export TEMP=/tmp
export TMPDIR=/tmp
export EDITOR=vi
export ORACLE_TERM=xterm
export PATH=\$ORACLE_HOME/bin:\$PATH
export NLS_LANG=american_america.al32utf8
export ORA_NLS10=\$ORACLE_HOME/nls/data
ulimit -u 16384 -n 63536

export RLWRAP_EDITOR=\"vim +%L -c 'syntax on' -c 'set filetype=sql'\"
alias sysdba='rlwrap -m -s5000 sqlplus / as sysdba'
alias rman='rlwrap rman'

alias via=\"vim -R \$ORACLE_BASE/diag/rdbms/\$(echo \$ORACLE_UNQNAME | tr 'A-Z' 'a-z')/\$ORACLE_SID/trace/alert_\$ORACLE_SID.log\"
alias vil=\"vim -R \$ORACLE_BASE/diag/tnslsnr/\$(uname -n)/listener/trace/listener.log\"

export PS1=\"\$ORACLE_SID:\\h \\w$ \"

" > ~oracle/.bashrc

#######################################################################
# install oracle
#######################################################################

echo "
ssh -X oracle@$(hostname -s)

### Install Oracle Application ###
cd /srv/u00/setup/12.1.0SE/database
/srv/u00/setup/12.1.0SE/database/runInstaller
#MyNote: /srv/u00/setup/12.1.0SE/database/runInstaller -responseFile /srv/u00/setup/12.1.0SE/database/runInstaller.rsp [-silent]
   Select Installation Option: Install database software only
   Grid Installation Options: Single instance database installation
   Select Product Languages: English, German
   Select Database Option: SE or EE
   Specify Installation Location: do not change
      $OBASE
      $OBASE/product/12.1.0/db1
   Create Inventory: do not change
      $ORA_APP/oraInventory
      oraInventory Group Name: dba
   Privileged Operating Sysem Groups: select dba for all
   Perform Prerequisite Checks: fix as needed (shmmax,...)
      Ignore: Swap Size and ksh
   Install, execute as root when asked for:
      $ORA_APP/oraInventory/orainstRoot.sh
      $OBASE/product/12.1.0/db1/root.sh
   Software Installation finished.

### Create Database ###
dbca

Example Config:
---------------
DATAFILES
  $ROOT/u01/oradata/$SID/

LOGFILES (50MB)
  GROUP 1
    $ROOT/u01/oradata/$SID/redog1m1.rdo
    $ROOT/u02/oradata/$SID/redog1m2.rdo
  GROUP 2
    $ROOT/u02/oradata/$SID/redog2m1.rdo
    $ROOT/u03/oradata/$SID/redog2m2.rdo
  GROUP 3
    $ROOT/u03/oradata/$SID/redog3m1.rdo
    $ROOT/u01/oradata/$SID/redog3m2.rdo

CONTROL FILES
    $ROOT/u01/oradata/$SID/control01.ctl
    $ROOT/u02/oradata/$SID/control02.ctl
    $ROOT/u03/oradata/$SID/control03.ctl

LOG_ARCHIVE_DEST 
   $ROOT/u03/arch/$SID/*.arc

FLASH_DEST 
   $BKP/$SID

CHARACTER SET AL32UTF8
---------------

Database Operation: Create Database
Creation Mode:
   (*) Advanced Mode
      DB Template: General Purpose or Transaction Processing
      DB Idendification (GDN & SID): $SID
         [ ] Create as Container DB
      Management Options
         [x] Configure Enterprise Manager
            Port: 5500
         [ ] Register with EM Cloud Control
      Database Credentials
         (*) Use the Same Administrative Password for All Accounts
      Network Configuration
         [x] Create a New Listener
            Listener Name: $SID
            Listener Port: 1521
      Storage Locations
         (*) Use Common Location for All Database Files
            File Location: $ROOT/u01/oradata
         Recovery files Storage Type: File System
            [x] Specify Fast Recovery Area
               Fast Recovery Area: $ROOT/u04/flash/$SID
            [x] Enable Archiving
               Select $ROOT/u03/arch/$SID/*.arc if you do not want
               to integrate them into Flash.
      Initialization Parameters
         Character Sets: Use Unicode AL32UTF8
            National Character Set: UTF8
      Creation Options
         Customize Storage Locations
            *** SET AS DESCRIBED ABOVE***
      Prerequisite Checks
         *** Everything has to be ok ***
      Finish

   ### INSTALL DATAPUMP FULL BACKUP IF NEEDED ###
   wget -O - http://www.bitbull.ch/dl/scripts/ora_12c_dp_backup.sh > /usr/local/bin/ora_12c_dp_backup.sh
   chmod 755 /usr/local/bin/ora_12c_dp_backup.sh
   vi /usr/local/bin/ora_12c_dp_backup.sh # configure vars
   su - oracle
      mkdir -p /srv/u01/dp
      sysdba
         create or replace directory expdp_dir as '/srv/u01/dp';
         @$OBASE/product/12.1.0/db1/rdbms/admin/catproc.sql
         @$OBASE/product/12.1.0/db1/rdbms/admin/utlrp.sql
     /usr/local/bin/ora_12c_dp_backup.sh
     cat /srv/u01/dp/fullbackup.log

   ### INSTALL AUTOSTART SCRIPT ###
   wget -O - http://www.bitbull.ch/dl/scripts/orainit-12c.sh > /etc/init.d/orainit
   chmod 700 /etc/init.d/orainit
   vi /etc/init.d/orainit # configure vars
   chkconfig --add orainit
   chkconfig orainit on
   service orainit stop
   service orainit status ; echo $?
   service orainit start
   service orainit status ; echo $?

   ### INSTALL RMAN BACKUP ###


   Enterprise Manager Login:
      https://$OIP:5500/em
         User: SYS
"
# HOWTO REMOVE COMPLETE ORACLE INSTALLATION
# pkill -9 -u oracle
# userdel -r oracle
# groupdel dba
# rm -rf $ROOT/u0?/{home,app,oracle,oradata,arch,flash} /etc/ora* /usr/local/bin/*ora* /usr/local/bin/dbhome
#
################################################################################
# $Log: oracle-12c-install.sh,v $
# Revision 1.3  2015/11/21 19:22:20  chris
# typo in alias vil and via
#
# Revision 1.2  2015/11/21 12:48:07  chris
# updated installation dialog for software and db installation
#
# Revision 1.1  2015/11/19 15:21:35  chris
# Initial revision
#
