#!/usr/bin/env ansible-playbook 
---
- hosts: localhost
  vars:
  vars_prompt:
    - name: vm_name
      prompt: "Name of VM"
      private: no
  tasks:
  - name: Power on VM
    vmware_guest_powerstate:
      hostname: "{{ vcenter_api_url }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ vm_name }}"
      state: powered-on
    delegate_to: localhost

