#!/usr/bin/env ansible-playbook 
---
- hosts: localhost
  vars:
  vars_prompt:
    - name: vm_name
      prompt: "Name of VM"
      private: no
  tasks:
  - name: Get VM Snapshots
    vmware_guest_snapshot_info:
      hostname: "{{ vcenter_api_url }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ vcenter_datacenter }}"
      folder: "{{ vcenter_vm_folder}}"
      validate_certs: no
      name: "{{ vm_name }}"
    register: snapshot_info
    delegate_to: localhost
  - debug: var=snapshot_info.guest_snapshots.snapshots

